### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#70]
If you are open to contributions, please mention so in the documentation as well as provide guidance on how to contribute to the repository. For example, are there particular branches that you would like pull requests to based off of (dev and docs only?), or are you okay with pull requests based on master?

**Comment by theonlydvr** [comment]
Thank you for noticing this. I added some details to the README and home page of the documentation that links out to a more detailed CONTRIBUTING.md.
