### ISSUE TITLE
creating source feedback

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#74]
I am going through the process of adding a source and have a couple of suggestions that may help the user. 

When I first went to add a video, the program crashed. 
![CleanShot 2024-04-19 at 14 13 02](https://github.com/tne-lab/py-behav-box-v2/assets/8128628/15e7d4c8-9fba-411e-b874-99135e847b1c)

The cause was that I was missing opencv. It would be nice if you could prevent an ignorant user like myself from crashing the program by adding a try except clause such as:

```python
try: 
    import cv2
except:
    # show a dialog explaining that the user needs to install opencv using pip install pybehave[video] or link to the documentation
```

The docs do mention how to install the extra dependencies [here](https://py-behav-box-v2.readthedocs.io/en/latest/#install-with-pip). I suggest reiterating this information of how to add the dependency [here](https://py-behav-box-v2.readthedocs.io/en/latest/sources/#videosource) where at the moment it only describes that `opencv-python` is required, not how to add it.

Another suggestion is to add labels/descriptions of the attributes or a link to [documentation](https://py-behav-box-v2.readthedocs.io/en/latest/sources/#videosource) directly in this dialog (and other SourceParametersDialogs).

![CleanShot 2024-04-19 at 14 31 17](https://github.com/tne-lab/py-behav-box-v2/assets/8128628/6e95fd1b-d817-43ae-a25a-c1340eed1951)

A link to [included sources docs](https://py-behav-box-v2.readthedocs.io/en/latest/sources/#included-sources) in this dialog may be useful as well:
![CleanShot 2024-04-19 at 15 02 18](https://github.com/tne-lab/py-behav-box-v2/assets/8128628/aaef798b-91de-414d-916d-5a35c12a53b1)

**Comment by theonlydvr** [comment]
This is a great suggestion and something I've been interested in adding for a little while now. Your suggestion to catch it at the import point made this really straightforward and clean to implement. Now, if you try to use a feature that requires an extra, a dialog like the below will pop up:
![image](https://github.com/tne-lab/py-behav-box-v2/assets/8806970/22d2fc75-e552-4d5c-8aef-9525073cd73f)
I've also made it so the '?' buttons in the two dialogs you sent link out to the corresponding documentation pages. I'll also work on adding the same feature for Widgets and EventLoggers.
