### ISSUE TITLE
faster task development cycle?

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#79]
I am writing a new task but only see my changes reflected if I restart pyBehave. Is there a faster way to refresh/reload a task and taskGUI without having to restart the program (and re-add the task)?

**Comment by theonlydvr** [comment]
Good idea, I think I could implement this using one of the reload modules. I think I could add a reload option in the dropdown when a ChamberWidget is right clicked.

**Comment by theonlydvr** [comment]
This feature should now be available as a right-click option from the ChamberWidget in the latest commit on the dev branch.

**Comment by alustig3** [comment]
works great. Thanks!
