### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by alustig3** [tne-lab/py-behav-box-v2#83]
- change `File->Add task` to `File->Add Chamber`
- change `right-click->Clear Chamber` to `right-click->Remove Chamber`
- when there is an error, it isn't always obvious to the user that something is wrong unless you look at the terminal. If possible, add some solution that whenever an error occurs, Qt indicates somehow to the user that an error has occurred (have a qmessagebox pop up saying an error has occurred and the user should check the terminal or add a status bar to the window and show an error status)
- add a description and link to docs to the github **About** section
![CleanShot 2024-04-30 at 14 32 35](https://github.com/tne-lab/py-behav-box-v2/assets/8128628/9eaf7c84-65ca-4b8b-b1a5-cf542f12413c)

**Comment by theonlydvr** [comment]
On the error pop-up point, many errors should already be popping up as QMessageBoxes. If you have examples where this didn't happen, could you send them over so I can make sure they're integrated into the existing error forwarding system?

**Comment by alustig3** [comment]
If I add `1/0` to the end of my pygame task GUI initialize(), the ZeroDivision error is only shown in the terminal.

**Comment by theonlydvr** [comment]
GUI errors have now been added to the error handling system with e3aff9b59d768518e6cd2d8d3d52ad1132b7a4ad
